# Change these first
owner: rhsCZ # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: rhscz.eu
    url: https://rhscz.eu
  - name: search.rhscz.eu
    url: https://search.rhscz.eu
  - name: rhsCZ vps1
    check: "tcp-ping"
    url: vps.rhscz.eu
    port: 22
  - name: rhsCZ vps2
    check: "tcp-ping"
    url: vps2.rhscz.eu
    port: 22
  - name: rhsCZ vps3
    check: "tcp-ping"
    url: vps3.rhscz.eu
    port: 22
  - name: rhsCZ vps4
    check: "tcp-ping"
    url: vps4.rhscz.eu
    port: 22

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.rhscz.eu
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: rhsCZ Uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
